### ISSUE TITLE
Everybody Commit Code

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/ProjectCrystalBlue#12]
Right now (Feb. 16) all there is only one commit https://github.com/SCCapstone/ProjectCrystalBlue/commit/b7eee323b84160da96fe139296110fc6f8f9d69d  by @mcgrawr and zero commits by @awesomejohnson

**Comment by hoodlm** [comment]
Most of Ryan's commits are on the iOS repository.
https://github.com/SCCapstone/ProjectCrystalBlue-iOS/commits/master

**Comment by josemvidal** [comment]
Ok. Please add a link to that repo to this repo's README, so I won't forget again.

**Comment by hoodlm** [comment]
Done
