### ISSUE TITLE
User can add Photos to samples

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/ProjectCrystalBlue#16]

**Comment by hoodlm** [comment]
Requests from barbeau (this also concerns @mcgrawr )

> for the image types, let's use in this order:
> far outcrop photo
> mid-range outcrop photo
> close outcrop photo
> slab image
> microscopy image
> other
> 
> if possible, it would be nice if i could save multiple images under a few of the categories (especially microscopy image and other). is there an automatic way to append a digit to the end of a category title if multiple images are assigned (e.g., "microscopy image 2"), or will it only accept one and thus overwrite?

We'll implement a front-end image addition screen on the OS X client, then work together to set it up in iOS on Saturday.

**Comment by hoodlm** [comment]
Completed image implementation. Tested on both OS X and iOS clients.
