### ISSUE TITLE
Create three Persona wiki pages

### ISSUE THREAD

**Issue by hoodlm** [SCCapstone/ProjectCrystalBlue#3]
Add at least three personas, one wiki page for each, to your wiki. These should cover 3 distinct user-types for your app. We discussed personas in our Design Process lecture, for more details read this article on Personas. Each Persona must have a name, photo, and personal history.

http://www.cse.sc.edu/capstone/milestone/project-description

**Comment by awesomejohnson** [comment]
I have finished the field researcher persona. Let me know, or edit it, if it needs work.

**Comment by hoodlm** [comment]
It's a good start with the background and such, but I think you should elaborate a bit more on how our system would relate to him, by stating the problems he has with manual data entry. something along the lines of "he wishes he could more easily access data about past samples when he's in the field without an internet connection" and "after returning from the field, synchronizing his data with other researchers is a pain in the ass".

Also - I think it's a requirement that all personas have a picture associated with them. A generic picture similar to this one would be ok: http://www.news.wisc.edu/newsphotos/images/geology_trip_dig_bone01.jpg

**Comment by awesomejohnson** [comment]
I revised it some. I already did have a picture associated with it. I don't know if it wasn't showing or something. Let me know about that because it shows up for me when I access the page.
