### ISSUE TITLE
OS X: Home Screen table scrolls out of boundary.

### ISSUE THREAD

**Issue by ghost** [SCCapstone/ProjectCrystalBlue#42]
In the osx app, user is able to scroll past the edges of the table with out any sort of bounce back to center.

**Comment by ghost** [comment]
This is not consistent, but does happen.

**Comment by hoodlm** [comment]
We have not been able to recreate this issue - do you know of any particular circumstances that make it more likely to happen? Can you show us a screenshot of exactly what's happening?

**Comment by hoodlm** [comment]
I'm fairly certain that this was caused by NSAlerts being called from background threads, as we haven't seen this issue in awhile. Re-open if anyone encounters this problem again.
