### ISSUE TITLE
OS X: When sync button clicked, the user is not notified that anything is happening.

### ISSUE THREAD

**Issue by ghost** [SCCapstone/ProjectCrystalBlue#43]
With a slow network connection, the button simply remains depressed. This looks very much like a freeze.

**Comment by hoodlm** [comment]
@justbaum30  added a progress bar modal for this.

https://github.com/SCCapstone/ProjectCrystalBlue/commit/6176ae79cd50a8d0bb1f343e6c9be8bcee7df39f
