### ISSUE TITLE
OS X: When uploading new photo for source, if loading is slow, it feels like a freeze

### ISSUE THREAD

**Issue by ghost** [SCCapstone/ProjectCrystalBlue#44]
Some sort of status indicator seems necessary.

**Comment by hoodlm** [comment]
Adding loading sheets to image uploads: https://github.com/SCCapstone/ProjectCrystalBlue/commit/86a535b617af3b43494ab4d0b72a600b418ecc20 and to CSV imports: https://github.com/SCCapstone/ProjectCrystalBlue/commit/08543d7947ed0387b503ac486fdf5ea5b88228f0
