### ISSUE TITLE
OS X: Toolbar disabled after failed source addition.

### ISSUE THREAD

**Issue by ghost** [SCCapstone/ProjectCrystalBlue#45]
When attempting to create a new source, if the key is not unique, clicking the cancel button leaves all of the toolbar buttons disabled.

**Comment by hoodlm** [comment]
@justbaum30 - possible solution we can to look into
http://stackoverflow.com/questions/4473662/how-to-force-nstoolbar-validation

**Comment by hoodlm** [comment]
note for later: this also appears after the user imports/exports (basically anytime we call "runModal" on an NSAlert)

**Comment by justbaum30** [comment]
It appears this is fixed.
