### ISSUE TITLE
OS X: Clicking the X in the corner of the app leaves it running but unable to open.

### ISSUE THREAD

**Issue by ghost** [SCCapstone/ProjectCrystalBlue#46]
The application is still running in the dock, but clicking it in the dock does nothing. The user must manually quit it from there to open it again.

**Comment by hoodlm** [comment]
If the user closes the main window, then the entire application will now quit.

https://github.com/SCCapstone/ProjectCrystalBlue/commit/5356ab62e6dfe2bbc11570303e7f79ce92259b20
