### ISSUE TITLE
Some new Split/Procedure-related features (requested by DLB)

### ISSUE THREAD

**Issue by hoodlm** [SCCapstone/ProjectCrystalBlue#57]
1. A way to undo/delete a procedure (As of right now the only way to do this is to manually edit CSV files)
2. List Jaw Crush before Pulverize in the list of Procedures, since we always JC first
3. Gemeni isn't spelled Gemini, but Gemeni
4. Add another procedure: Archive, and include a space to include the Archive Collection name (e.g., Museum, Rainy Day, etc.)? This should go near the top of the procedures list.
5. Under the Sieve procedure, can you leave it at just 'Sieve' and allow a space for user to enter sieve size?
6. Add another procedure: Mount*\* and include a space to indicate mount type (e.g., SEM stub, grain mount, epoxy ring, etc.)
7. Add another procedure: Split**\* in which case a representative subset of material would yield a new sample and head in another direction
8. Add another procedure: Pick**\* and include a space to indicate what was picked?
9. Add another procedure: Analyze***\* and include a space to indicate what analysis was conducted?
10. Can we include a column/entry called n (for number of samples, aka splits) that auto-sums the number of samples/splits per source (aka sample)
11. Can we include a column/entry called 'Last Procedure' that indicates the last procedure performed, the date thereof and maybe the person who did it?
12. A way to designate certain samples as 'Active Samples' -- i.e., ones we are presently working on? A color scheme might work best here, as might a flag of some sort.

*\* divergent OR non-divergent procedure: e.g., sometimes we mount all grains, sometimes we mount some (Mount DOWN?), and save the rest (Mount UP?); sometimes we send an entire split to another lab, sometimes we keep some for ourselves, etc.
**\* divergent procedure -- like Gemeni, Heavy liquids, etc., this generates two splits, UP and DOWN for lack of better terms
***\* some analyses are destructive, and others are not.

**Comment by mcgrawr** [comment]
did 2 and 3 for iOS and OSX (and tested to make sure nothing changed)

For #1 there needs to be a function written to delete a procedure record... not quite sure how to do that one

**Comment by hoodlm** [comment]
You can use this method

``` Objective-C
+(NSArray *)procedureRecordArrayFromList:(NSString *)recordList
```

Then manually remove the desired procedure from the Array, create a comma-separated list of the RecordProcedures, then set the comma-separated list to the TAGS attribute like this:

``` Objective-C
[split.attributes setObject:commaSeparatedProcedureRecords forKey:SPL_TAGS];
```

That's pretty messy though. As Justin mentioned, I might be doing a lot of refactoring of how Procedures are set up, so don't worry about this if you don't want to. I'll probably be adding a high-level class analogous to SampleImageUtils to abstract a lot of that away.

**Comment by mcgrawr** [comment]
i tried but I couldn't get the deleting to stick after leaving the view and yes it was very messy. I suppose I will wait.
